GUI
webermael/NAWIMAT-Projektarbeit pull request #19
Opened 2024-09-16 08:22 UTC by webermael

Added graphical user interface
- Start Window
    - Start Simulation
    - Open Settings

2024-09-17 22:02 UTC, webermael commented
Questions:
- Any thoughts about the layout in general?
- What has to be changed still?

2024-09-17 22:07 UTC, webermael commented
Code:
- Add back class Config (inheritance)?
- Remove class Slider?

2024-09-19 09:18 UTC, WanderJohnie approved these changes
Good code (Fu tk)

2024-09-19 09:33 UTC, graberyanis requested changes
Time is ticking (but we still got time) :)

2024-09-19 09:33 UTC, graberyanis commented on src/main.py
> +from utils.gui import SaveWindow
can't you have these all in 1 line?

2024-09-19 09:33 UTC, graberyanis commented on src/main.py
> +                same_file = False
this line is not necessary (I think)

2024-09-19 09:33 UTC, graberyanis commented on src/main.py
> +                same_file = False
This line is also redundant

2024-09-19 09:33 UTC, graberyanis commented on src/simulation.py
I feel like you can revert these changes, as we made them for running while using a single simulation object instead of redefining it (could be wrong)

2024-09-19 09:33 UTC, graberyanis commented on src/utils/interface_values.py
We'll see about the names and the values but good for now

2024-09-19 09:43 UTC, webermael commented on src/utils/interface_values.py
perfect

2024-09-19 09:44 UTC, graberyanis approved these changes
Very Good

2024-09-19 09:45 UTC, merged